# Generated by Django 5.2.16 on 2026-07-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='core_transa_user_id_7acc13_idx',
            old_name='core_transa_user_id_9e5e77_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='core_transa_referen_61d5aa_idx',
            old_name='core_transa_referen_2e1f7a_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='core_transa_status_288ab7_idx',
            old_name='core_transa_status_9b6e2a_idx',
        ),
    ]
