# Generated by Django 5.2.16 on 2026-07-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_core_transa_user_id_9e5e77_idx_core_transa_user_id_7acc13_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paystack_customer_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
