# Generated by Django 5.2.16 on 2026-08-05 15:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_paystack_customer_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('airtime', 'Airtime'), ('electricity', 'Electricity')], max_length=15, unique=True)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('data', 'Data'), ('cable', 'Cable TV')], max_length=10)),
                ('network', models.CharField(help_text='MTN, AIRTEL, GLO, 9MOBILE, DSTV, GOTV, STARTIMES', max_length=20)),
                ('provider_plan_id', models.CharField(help_text='The plan_id CheapDataHub expects', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('validity', models.CharField(blank=True, default='', max_length=50)),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='What CheapDataHub charges you', max_digits=10)),
                ('commission_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount (₦)')], default='percent', max_length=10)),
                ('commission_value', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['network', 'cost_price'],
                'unique_together': {('service', 'network', 'provider_plan_id')},
            },
        ),
    ]
