# Generated by Django 5.2.16 on 2026-08-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servicecommission_serviceplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, help_text='What CheapDataHub charges you (API Price)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='network',
            field=models.CharField(help_text='MTN, AIRTEL, GLO, 9MOBILE, DSTV, GOTV, STARTIMES, AEDC, EKEDC, etc.', max_length=30),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='provider_plan_id',
            field=models.CharField(help_text='The plan_id/ID CheapDataHub expects in API calls', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='service',
            field=models.CharField(choices=[('data', 'Data'), ('cable', 'Cable TV'), ('electricity', 'Electricity')], max_length=15),
        ),
    ]
