# Generated by Django 5.2.16 on 2026-08-05 21:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_serviceplan_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='commission_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
